# Generated by Django 3.0 on 2019-12-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('breed', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('favourite_food', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_contact_info', models.TextField(max_length=50)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dad', to='home.Dog')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mom', to='home.Dog')),
            ],
        ),
    ]
